/**
 * Devnexes AI v2 — Supervisor Layer
 * Validates execution graphs generated by the Thinking Node before execution begins.
 */

import { getToolById } from './toolRegistry.js';

export function validateExecutionGraph(plan, registeredTools = []) {
  const errors = [];

  if (!plan || typeof plan !== 'object') {
    return { valid: false, errors: ['Execution plan is empty or non-object'], replan: true };
  }

  if (!Array.isArray(plan.nodes) || plan.nodes.length === 0) {
    return { valid: false, errors: ['Execution plan contains no nodes'], replan: true };
  }

  const seenIds = new Set();

  for (let i = 0; i < plan.nodes.length; i++) {
    const node = plan.nodes[i];
    const nodeId = node.id || `node_${i + 1}`;

    if (seenIds.has(nodeId)) {
      errors.push(`Duplicate node ID detected: ${nodeId}`);
    }
    seenIds.add(nodeId);

    // Validate tool availability if tool specified
    if (node.tool) {
      const toolDef = getToolById(node.tool);
      if (!toolDef && !['codeArtifact', 'webSearch', 'symbolSearch', 'createFile', 'browserPreview', 'reflectionAudit', 'imageGeneration'].includes(node.tool)) {
        errors.push(`Node '${nodeId}' requests unknown tool: '${node.tool}'`);
      }
    }

    // Validate dependencies
    if (Array.isArray(node.dependsOn)) {
      for (const depId of node.dependsOn) {
        if (!seenIds.has(depId)) {
          errors.push(`Node '${nodeId}' depends on unknown prior node '${depId}'`);
        }
      }
    }
  }

  if (errors.length > 0) {
    console.warn('[Supervisor] Graph validation failed:', errors);
    return { valid: false, errors, replan: true };
  }

  return { valid: true, errors: [], replan: false };
}
